import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
  BeforeInsert,
} from 'typeorm';
import { Valorizacion } from './valuation.model';
import { User } from './user.model';

export type EstadoPago = 'PENDIENTE' | 'CONFIRMADO' | 'RECHAZADO' | 'ANULADO';

export type MetodoPago = 'TRANSFERENCIA' | 'CHEQUE' | 'EFECTIVO' | 'LETRA' | 'DEPOSITO' | 'OTROS';

export type TipoComprobante = 'FACTURA' | 'RECIBO' | 'BOLETA' | 'OTROS';

@Entity('registro_pago', { schema: 'equipo' })
export class PaymentRecord {
  @PrimaryGeneratedColumn()
  id!: number;

  // Foreign keys
  @Column({ name: 'valorizacion_id', type: 'integer' })
  @Index('idx_registro_pago_valorizacion')
  valuationId!: number;

  @ManyToOne(() => Valorizacion)
  @JoinColumn({ name: 'valorizacion_id' })
  valuation?: Valorizacion;

  @Column({ name: 'contrato_id', type: 'integer', nullable: true })
  @Index('idx_registro_pago_contrato')
  contractId?: number;

  @Column({ name: 'proyecto_id', type: 'integer', nullable: true })
  @Index('idx_registro_pago_proyecto')
  projectId?: number;

  // Payment identification
  @Column({ name: 'numero_pago', type: 'varchar', length: 50, unique: true })
  @Index('idx_registro_pago_numero')
  paymentNumber!: string;

  @Column({ name: 'fecha_pago', type: 'date' })
  @Index('idx_registro_pago_fecha')
  paymentDate!: Date;

  @Column({ name: 'monto_pagado', type: 'decimal', precision: 12, scale: 2 })
  amountPaid!: number;

  @Column({ name: 'moneda', type: 'varchar', length: 3, default: 'PEN' })
  currency!: string;

  @Column({
    name: 'tipo_cambio',
    type: 'decimal',
    precision: 10,
    scale: 4,
    nullable: true,
  })
  exchangeRate?: number;

  // Payment method details
  @Column({ name: 'metodo_pago', type: 'varchar', length: 50 })
  paymentMethod!: MetodoPago;

  @Column({ name: 'banco_origen', type: 'varchar', length: 100, nullable: true })
  originBank?: string;

  @Column({ name: 'banco_destino', type: 'varchar', length: 100, nullable: true })
  destinationBank?: string;

  @Column({ name: 'cuenta_origen', type: 'varchar', length: 50, nullable: true })
  originAccount?: string;

  @Column({ name: 'cuenta_destino', type: 'varchar', length: 50, nullable: true })
  destinationAccount?: string;

  @Column({ name: 'numero_operacion', type: 'varchar', length: 100, nullable: true })
  operationNumber?: string;

  @Column({ name: 'numero_cheque', type: 'varchar', length: 50, nullable: true })
  checkNumber?: string;

  // Receipt/Invoice details
  @Column({ name: 'comprobante_tipo', type: 'varchar', length: 20, nullable: true })
  receiptType?: TipoComprobante;

  @Column({ name: 'comprobante_numero', type: 'varchar', length: 50, nullable: true })
  receiptNumber?: string;

  @Column({ name: 'comprobante_fecha', type: 'date', nullable: true })
  receiptDate?: Date;

  // Status and reconciliation
  @Column({ name: 'estado', type: 'varchar', length: 20, default: 'CONFIRMADO' })
  @Index('idx_registro_pago_estado')
  status!: EstadoPago;

  @Column({ name: 'conciliado', type: 'boolean', default: false })
  @Index('idx_registro_pago_conciliado')
  reconciled!: boolean;

  @Column({ name: 'fecha_conciliacion', type: 'timestamp', nullable: true })
  reconciliationDate?: Date;

  // Additional info
  @Column({ name: 'observaciones', type: 'text', nullable: true })
  observations?: string;

  @Column({ name: 'referencia_interna', type: 'varchar', length: 100, nullable: true })
  internalReference?: string;

  // Audit fields
  @Column({ name: 'registrado_por_id', type: 'integer', nullable: true })
  registeredBy?: number;

  @ManyToOne(() => User)
  @JoinColumn({ name: 'registrado_por_id' })
  registeredByUser?: User;

  @Column({ name: 'aprobado_por_id', type: 'integer', nullable: true })
  approvedBy?: number;

  @ManyToOne(() => User)
  @JoinColumn({ name: 'aprobado_por_id' })
  approvedByUser?: User;

  @Column({ name: 'fecha_registro', type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
  registrationDate!: Date;

  @Column({ name: 'fecha_aprobacion', type: 'timestamp', nullable: true })
  approvalDate?: Date;

  // Timestamps
  @CreateDateColumn({ name: 'created_at' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt!: Date;

  // Generate payment number before insert if not provided
  @BeforeInsert()
  async generatePaymentNumber() {
    if (!this.paymentNumber) {
      // Payment number will be generated by the service
      // This is just a placeholder to ensure it's never null
      this.paymentNumber = `PAG-${new Date().getFullYear()}-TEMP-${Date.now()}`;
    }
  }
}
