import { MigrationInterface, QueryRunner } from "typeorm";

export class AddProviderAuditLogTable1771007043424 implements MigrationInterface {
    name = 'AddProviderAuditLogTable1771007043424'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_contacts" DROP CONSTRAINT "FK_f91dec55bcc33c2dfbd69bab06b"`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_financial_info" DROP CONSTRAINT "fk_provider_financial_info_provider"`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" DROP CONSTRAINT "FK_6c0ed07a84d3a9462220439288e"`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" DROP CONSTRAINT "FK_1c8b4e02ce012b8bce16b8c72ea"`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" DROP CONSTRAINT "FK_f54e0a924efa9693f390959e398"`);
        await queryRunner.query(`ALTER TABLE "rrhh"."detalle_tareo" DROP CONSTRAINT "FK_673ffb31e73bdf4f7ae6538bfcb"`);
        await queryRunner.query(`ALTER TABLE "sistema"."user_projects" DROP CONSTRAINT "fk_user_projects_user"`);
        await queryRunner.query(`ALTER TABLE "sistema"."user_projects" DROP CONSTRAINT "fk_user_projects_project"`);
        await queryRunner.query(`DROP INDEX "proveedores"."idx_provider_contacts_provider_id"`);
        await queryRunner.query(`DROP INDEX "proveedores"."idx_provider_contacts_is_primary"`);
        await queryRunner.query(`DROP INDEX "proveedores"."idx_provider_financial_info_provider_id"`);
        await queryRunner.query(`DROP INDEX "proveedores"."idx_provider_financial_info_is_primary"`);
        await queryRunner.query(`DROP INDEX "equipo"."idx_maintenance_schedules_equipment"`);
        await queryRunner.query(`DROP INDEX "equipo"."idx_maintenance_schedules_status"`);
        await queryRunner.query(`DROP INDEX "equipo"."idx_maintenance_schedules_next_due"`);
        await queryRunner.query(`DROP INDEX "sistema"."idx_user_projects_user"`);
        await queryRunner.query(`DROP INDEX "sistema"."idx_user_projects_project"`);
        await queryRunner.query(`DROP INDEX "sistema"."idx_user_projects_unique"`);
        await queryRunner.query(`CREATE TABLE "administracion"."empresa" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "subdomain" character varying(100) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'active', "settings" jsonb NOT NULL DEFAULT '{}', "subscription" jsonb NOT NULL DEFAULT '{}', "contact_info" jsonb NOT NULL DEFAULT '{}', "billing_info" jsonb NOT NULL DEFAULT '{}', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe7bd06cb972d5d58de84b25280" UNIQUE ("subdomain"), CONSTRAINT "PK_bee78e8f1760ccf9cff402118a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "equipo"."registro_pago" ("id" SERIAL NOT NULL, "valorizacion_id" integer NOT NULL, "contrato_id" integer, "proyecto_id" integer, "numero_pago" character varying(50) NOT NULL, "fecha_pago" date NOT NULL, "monto_pagado" numeric(12,2) NOT NULL, "moneda" character varying(3) NOT NULL DEFAULT 'PEN', "tipo_cambio" numeric(10,4), "metodo_pago" character varying(50) NOT NULL, "banco_origen" character varying(100), "banco_destino" character varying(100), "cuenta_origen" character varying(50), "cuenta_destino" character varying(50), "numero_operacion" character varying(100), "numero_cheque" character varying(50), "comprobante_tipo" character varying(20), "comprobante_numero" character varying(50), "comprobante_fecha" date, "estado" character varying(20) NOT NULL DEFAULT 'CONFIRMADO', "conciliado" boolean NOT NULL DEFAULT false, "fecha_conciliacion" TIMESTAMP, "observaciones" text, "referencia_interna" character varying(100), "registrado_por_id" integer, "aprobado_por_id" integer, "fecha_registro" TIMESTAMP NOT NULL DEFAULT now(), "fecha_aprobacion" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6d598d94a2175cca0058986cd8e" UNIQUE ("numero_pago"), CONSTRAINT "PK_b3ab30de18c95beb656c08393b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_registro_pago_valorizacion" ON "equipo"."registro_pago" ("valorizacion_id") `);
        await queryRunner.query(`CREATE INDEX "idx_registro_pago_contrato" ON "equipo"."registro_pago" ("contrato_id") `);
        await queryRunner.query(`CREATE INDEX "idx_registro_pago_proyecto" ON "equipo"."registro_pago" ("proyecto_id") `);
        await queryRunner.query(`CREATE INDEX "idx_registro_pago_numero" ON "equipo"."registro_pago" ("numero_pago") `);
        await queryRunner.query(`CREATE INDEX "idx_registro_pago_fecha" ON "equipo"."registro_pago" ("fecha_pago") `);
        await queryRunner.query(`CREATE INDEX "idx_registro_pago_estado" ON "equipo"."registro_pago" ("estado") `);
        await queryRunner.query(`CREATE INDEX "idx_registro_pago_conciliado" ON "equipo"."registro_pago" ("conciliado") `);
        await queryRunner.query(`CREATE TABLE "proveedores"."proveedor_log" ("id" SERIAL NOT NULL, "proveedor_id" integer NOT NULL, "accion" character varying(50) NOT NULL, "campo" character varying(100), "valor_anterior" text, "valor_nuevo" text, "usuario_id" integer, "observaciones" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f9b18b9770e0bbb1e2816978e4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_proveedor_log_proveedor" ON "proveedores"."proveedor_log" ("proveedor_id") `);
        await queryRunner.query(`ALTER TABLE "sistema"."rol" DROP COLUMN "is_system"`);
        await queryRunner.query(`ALTER TABLE "sistema"."rol" DROP COLUMN "permissions"`);
        await queryRunner.query(`ALTER TABLE "equipo"."equipo" DROP COLUMN "creado_por"`);
        await queryRunner.query(`ALTER TABLE "equipo"."equipo" DROP COLUMN "actualizado_por"`);
        await queryRunner.query(`ALTER TABLE "equipo"."contrato_adenda" DROP COLUMN "modalidad"`);
        await queryRunner.query(`ALTER TABLE "equipo"."contrato_adenda" DROP COLUMN "minimo_por"`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_contacts" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_contacts" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_financial_info" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_financial_info" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "equipo"."equipo" ALTER COLUMN "estado" SET DEFAULT 'DISPONIBLE'`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."maintenance_type" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."interval_type" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."interval_value" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."auto_generate_tasks" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."last_completed_hours" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."next_due_hours" IS NULL`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_contacts" ADD CONSTRAINT "FK_f91dec55bcc33c2dfbd69bab06b" FOREIGN KEY ("provider_id") REFERENCES "proveedores"."proveedor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_financial_info" ADD CONSTRAINT "FK_1297f73e16740c031da11737aee" FOREIGN KEY ("provider_id") REFERENCES "proveedores"."proveedor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" ADD CONSTRAINT "FK_6c0ed07a84d3a9462220439288e" FOREIGN KEY ("equipment_id") REFERENCES "equipo"."equipo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" ADD CONSTRAINT "FK_1c8b4e02ce012b8bce16b8c72ea" FOREIGN KEY ("project_id") REFERENCES "proyectos"."edt"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" ADD CONSTRAINT "FK_f54e0a924efa9693f390959e398" FOREIGN KEY ("created_by") REFERENCES "sistema"."usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrhh"."detalle_tareo" ADD CONSTRAINT "FK_673ffb31e73bdf4f7ae6538bfcb" FOREIGN KEY ("tareo_id") REFERENCES "rrhh"."tareo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipo"."registro_pago" ADD CONSTRAINT "FK_df0abe8f1de40abd89f7b0446b1" FOREIGN KEY ("valorizacion_id") REFERENCES "equipo"."valorizacion_equipo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipo"."registro_pago" ADD CONSTRAINT "FK_c50390c5f453deb8ffdac5540b9" FOREIGN KEY ("registrado_por_id") REFERENCES "sistema"."usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipo"."registro_pago" ADD CONSTRAINT "FK_18c0ab2f4a0f35f52b7cb94532e" FOREIGN KEY ("aprobado_por_id") REFERENCES "sistema"."usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proveedores"."proveedor_log" ADD CONSTRAINT "FK_c9c8c4580f1180b816ccfd1e41f" FOREIGN KEY ("proveedor_id") REFERENCES "proveedores"."proveedor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proveedores"."proveedor_log" ADD CONSTRAINT "FK_61d05c1b65025525f26ad9823fc" FOREIGN KEY ("usuario_id") REFERENCES "sistema"."usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "proveedores"."proveedor_log" DROP CONSTRAINT "FK_61d05c1b65025525f26ad9823fc"`);
        await queryRunner.query(`ALTER TABLE "proveedores"."proveedor_log" DROP CONSTRAINT "FK_c9c8c4580f1180b816ccfd1e41f"`);
        await queryRunner.query(`ALTER TABLE "equipo"."registro_pago" DROP CONSTRAINT "FK_18c0ab2f4a0f35f52b7cb94532e"`);
        await queryRunner.query(`ALTER TABLE "equipo"."registro_pago" DROP CONSTRAINT "FK_c50390c5f453deb8ffdac5540b9"`);
        await queryRunner.query(`ALTER TABLE "equipo"."registro_pago" DROP CONSTRAINT "FK_df0abe8f1de40abd89f7b0446b1"`);
        await queryRunner.query(`ALTER TABLE "rrhh"."detalle_tareo" DROP CONSTRAINT "FK_673ffb31e73bdf4f7ae6538bfcb"`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" DROP CONSTRAINT "FK_f54e0a924efa9693f390959e398"`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" DROP CONSTRAINT "FK_1c8b4e02ce012b8bce16b8c72ea"`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" DROP CONSTRAINT "FK_6c0ed07a84d3a9462220439288e"`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_financial_info" DROP CONSTRAINT "FK_1297f73e16740c031da11737aee"`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_contacts" DROP CONSTRAINT "FK_f91dec55bcc33c2dfbd69bab06b"`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."next_due_hours" IS 'Equipment hours when next due'`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."last_completed_hours" IS 'Equipment hours when last completed'`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."auto_generate_tasks" IS 'Auto-generate scheduled tasks when due'`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."status" IS 'Status: active, inactive, suspended'`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."interval_value" IS 'Interval quantity (e.g., 250 hours, 30 days)'`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."interval_type" IS 'Interval unit: hours, days, weeks, months'`);
        await queryRunner.query(`COMMENT ON COLUMN "equipo"."maintenance_schedules"."maintenance_type" IS 'Type: preventive, corrective, predictive, etc.'`);
        await queryRunner.query(`ALTER TABLE "equipo"."equipo" ALTER COLUMN "estado" SET DEFAULT 'disponible'`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_financial_info" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_financial_info" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_contacts" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_contacts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "equipo"."contrato_adenda" ADD "minimo_por" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "equipo"."contrato_adenda" ADD "modalidad" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "equipo"."equipo" ADD "actualizado_por" integer`);
        await queryRunner.query(`ALTER TABLE "equipo"."equipo" ADD "creado_por" integer`);
        await queryRunner.query(`ALTER TABLE "sistema"."rol" ADD "permissions" jsonb`);
        await queryRunner.query(`ALTER TABLE "sistema"."rol" ADD "is_system" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`DROP INDEX "proveedores"."idx_proveedor_log_proveedor"`);
        await queryRunner.query(`DROP TABLE "proveedores"."proveedor_log"`);
        await queryRunner.query(`DROP INDEX "equipo"."idx_registro_pago_conciliado"`);
        await queryRunner.query(`DROP INDEX "equipo"."idx_registro_pago_estado"`);
        await queryRunner.query(`DROP INDEX "equipo"."idx_registro_pago_fecha"`);
        await queryRunner.query(`DROP INDEX "equipo"."idx_registro_pago_numero"`);
        await queryRunner.query(`DROP INDEX "equipo"."idx_registro_pago_proyecto"`);
        await queryRunner.query(`DROP INDEX "equipo"."idx_registro_pago_contrato"`);
        await queryRunner.query(`DROP INDEX "equipo"."idx_registro_pago_valorizacion"`);
        await queryRunner.query(`DROP TABLE "equipo"."registro_pago"`);
        await queryRunner.query(`DROP TABLE "administracion"."empresa"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_user_projects_unique" ON "sistema"."user_projects" ("user_id", "project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_projects_project" ON "sistema"."user_projects" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_projects_user" ON "sistema"."user_projects" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_maintenance_schedules_next_due" ON "equipo"."maintenance_schedules" ("next_due_date") WHERE ((status)::text = 'active'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_maintenance_schedules_status" ON "equipo"."maintenance_schedules" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_maintenance_schedules_equipment" ON "equipo"."maintenance_schedules" ("equipment_id") `);
        await queryRunner.query(`CREATE INDEX "idx_provider_financial_info_is_primary" ON "proveedores"."provider_financial_info" ("is_primary") `);
        await queryRunner.query(`CREATE INDEX "idx_provider_financial_info_provider_id" ON "proveedores"."provider_financial_info" ("provider_id") `);
        await queryRunner.query(`CREATE INDEX "idx_provider_contacts_is_primary" ON "proveedores"."provider_contacts" ("is_primary") WHERE (is_primary = true)`);
        await queryRunner.query(`CREATE INDEX "idx_provider_contacts_provider_id" ON "proveedores"."provider_contacts" ("provider_id") `);
        await queryRunner.query(`ALTER TABLE "sistema"."user_projects" ADD CONSTRAINT "fk_user_projects_project" FOREIGN KEY ("project_id") REFERENCES "proyectos"."edt"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sistema"."user_projects" ADD CONSTRAINT "fk_user_projects_user" FOREIGN KEY ("user_id") REFERENCES "sistema"."usuario"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrhh"."detalle_tareo" ADD CONSTRAINT "FK_673ffb31e73bdf4f7ae6538bfcb" FOREIGN KEY ("tareo_id") REFERENCES "rrhh"."tareo"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" ADD CONSTRAINT "FK_f54e0a924efa9693f390959e398" FOREIGN KEY ("created_by") REFERENCES "sistema"."usuario"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" ADD CONSTRAINT "FK_1c8b4e02ce012b8bce16b8c72ea" FOREIGN KEY ("project_id") REFERENCES "proyectos"."edt"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipo"."maintenance_schedules" ADD CONSTRAINT "FK_6c0ed07a84d3a9462220439288e" FOREIGN KEY ("equipment_id") REFERENCES "equipo"."equipo"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_financial_info" ADD CONSTRAINT "fk_provider_financial_info_provider" FOREIGN KEY ("provider_id") REFERENCES "proveedores"."proveedor"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "proveedores"."provider_contacts" ADD CONSTRAINT "FK_f91dec55bcc33c2dfbd69bab06b" FOREIGN KEY ("provider_id") REFERENCES "proveedores"."proveedor"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
