USE [master]
GO
/****** Object:  Database [dbBitCorp]    Script Date: 3/4/2026 11:33:41 AM ******/
CREATE DATABASE [dbBitCorp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbAramsa_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\dbAramsa.mdf' , SIZE = 36864KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbAramsa_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\dbAramsa.ldf' , SIZE = 28608KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [dbBitCorp] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbBitCorp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dbBitCorp] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dbBitCorp] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dbBitCorp] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dbBitCorp] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dbBitCorp] SET ARITHABORT OFF 
GO
ALTER DATABASE [dbBitCorp] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dbBitCorp] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dbBitCorp] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dbBitCorp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dbBitCorp] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dbBitCorp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dbBitCorp] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dbBitCorp] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dbBitCorp] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dbBitCorp] SET  ENABLE_BROKER 
GO
ALTER DATABASE [dbBitCorp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dbBitCorp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dbBitCorp] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dbBitCorp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dbBitCorp] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dbBitCorp] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [dbBitCorp] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dbBitCorp] SET RECOVERY FULL 
GO
ALTER DATABASE [dbBitCorp] SET  MULTI_USER 
GO
ALTER DATABASE [dbBitCorp] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dbBitCorp] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dbBitCorp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dbBitCorp] SET TARGET_RECOVERY_TIME = 120 SECONDS 
GO
ALTER DATABASE [dbBitCorp] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [dbBitCorp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [dbBitCorp] SET QUERY_STORE = ON
GO
ALTER DATABASE [dbBitCorp] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = ALL, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [dbBitCorp]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 8;
GO
ALTER DATABASE [dbBitCorp] SET  READ_WRITE 
GO
