#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm so WSL node/npx are used instead of Windows binaries
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

npx commitlint --edit "${1}" --config commitlint.config.js
